### ISSUE TITLE
Syntax highlight

### ISSUE THREAD

**Issue by magic890** [jacobwgillespie/language-hocon#1]
Hi Jacob,

nice work.
I'm still experiencing some issues with syntax highlight, see the attached screenshot.

<img width="1440" alt="screen shot 2015-11-19 at 10 14 48" src="https://cloud.githubusercontent.com/assets/1352670/11266699/b0346a44-8ea6-11e5-9972-2e17d9709a96.png">

Why some comments are highlighted in light blue and other are highlighted in grey?
Also the variable aren't always highlighted properly.

**Comment by jacobwgillespie** [comment]
Yeah, I've been working on that one - still a bit new to the grammar syntax.  Should be fixed shortly.

**Comment by jacobwgillespie** [comment]
This is fixed by v1.1.0 - there's still some remaining bugs (i.e. true is recognized as a constant in `asdf = true` but not `asdf=true` and variable interpolation isn't being highlighted in quoted strings, but I'll open other issues for those.
