### ISSUE TITLE
Triple Quotes Cause Improper Syntax Highlighting

### ISSUE THREAD

**Issue by kylezs** [jacobwgillespie/language-hocon#5]
Using triple quotes for multiline strings with concatenation of multiline strings causes the syntax highlighting to break
![screen shot 2018-07-12 at 2 00 57 pm](https://user-images.githubusercontent.com/8342557/42611981-116e276c-85dc-11e8-9665-b43ccfdca836.png)

**Comment by jeremybeard** [comment]
It looks like it's a problem for double-quoted strings too when using ":" between key and value:

![screen shot 2018-07-17 at 2 22 18 pm](https://user-images.githubusercontent.com/1947420/42837735-deb5cb5a-89cc-11e8-8656-cc8cba7baed6.png)

I've found the cause and put in PR #6 to fix it.

**Comment by jacobwgillespie** [comment]
Thanks to @jeremybeard this should be fixed and published as `v1.2.3` 🎉
